### ISSUE TITLE
remove haswell constraint from parallel_build.csh ?

### ISSUE THREAD

**Issue by gmao-rreichle** [GEOS-ESM/GEOSldas#287]
It looks like parallel_build.csh in GEOSldas uses a haswell constraint.
If I understand this correctly, this constraint originates from ./@env
But I might well be wrong. 
Is it correct that parallel_build.csh uses a haswell constraint?
If so, how can we get rid of it?
cc: @mathomp4 @biljanaorescanin

**Comment by weiyuan-jiang** [comment]
We can pass in -sky in the parallel_build.csh, i.e. change 
  ${ESMADIR}/@env/build.csh -esmadir $ESMADIR $argv
to
  ${ESMADIR}/@env/build.csh -esmadir $ESMADIR $argv -sky

Then it will choose skylake

**Comment by biljanaorescanin** [comment]
Maybe this page is outdated but isn't this coming from best practices for discover?
https://www.nccs.nasa.gov/nccs-users/instructional/using-discover/slurm-best-practices

**Comment by mathomp4** [comment]
@gmao-rreichle As @weiyuan-jiang you can indeed pass in `-sky` as an argument to `parallel_build.csh`. The reason why hasw is the default is because not every user at NCCS has access to the skylake nodes. In fact, to use `parallel_build.csh` with skylake, you'd probably have to add a qos and a partition as well as the constraint.

As the haswells are universally available to all users without the need for qos/partition, it defaults to that. If you'd like this to change, I can, but then I'd have to put in a *LOT* of protections to because the build would fail left and right if the wrong options were passed in.

Note that once Skylakes are generally available at NCCS, this could change, but then I'm sure I'll be getting issues where someone might try to build with MPT on Skylake and fail that way.

Note that I believe all machine types at NAS are supported out of box since all machine types are generally available at NAS.

**Comment by gmao-rreichle** [comment]
Thanks for your input @weiyuan-jiang @mathomp4 and @biljanaorescanin .
I'm not terribly familiar with who has access to which set of nodes, so maybe my comments don't make sense, after all.
But if memory serves me right, the "haswell" constraint dates from the SP1-to-SP3 transition of the O/S a few years ago.
Rather than requesting "sky" nodes, my thought was that we don't need a constraint at all.
If someone has access to more than one set of nodes, good for them.  If someone only has access to haswell, not specifying the constraint should make no difference.
I think we made a concerted effort a couple of months ago to remove all "haswell" constraints from GEOSldas.  It was my understanding that they're not needed and may, in future, become a problem.  I hope this wasn't misguided.
Perhaps @mathomp4 's comment is saying that having no constraint won't work well because other things will need to be specified.  If that's the case, so be it, and I'll gladly close the issue.  I'll ask @weiyuan-jiang to enlighten me off-line.

**Comment by gmao-rreichle** [comment]
Closing after consultation with @weiyuan-jiang .
