### ISSUE TITLE
Nightly test gnuglobalcs failing

### ISSUE THREAD

**Issue by biljanaorescanin** [GEOS-ESM/GEOSldas#318]
For past 5 days gnuglobalcs test is failing. Last change/ update from October 2nd was done by Matt
"In trying to fix up some AGCM nightly test issues, I saw that the LDAS GNU tests were still using GCC 9 and an older Baselibs. In order to "bring it in line" with what the current LDAS uses (6.0.16), I'm planning on updating the GNU runs to GCC 10 and 6.0.16." 

Weiyuan believes we can fix this by adding in:
GEOSldas_LDAS.rc  line:  WRITE_RESTART_BY_OSERVER: YES
and update MAPL new tag to new version v2.3.0 in components.yaml and Externals.cfg
cc: @gmao-rreichle  @weiyuan-jiang @mathomp4

**Comment by mathomp4** [comment]
Note that apparently I *was* using `WRITE_RESTART_BY_OSERVER: YES` with this test. I thought I turned it off, but I think a bad git commit must have happened. I'm currently running a test where I've turned it off just to see what happens.

Note no MAPL 2.3.0 in this.

**Comment by biljanaorescanin** [comment]
Two tests fail with this change.
**gnuglobal** in assim run for all land perturbations : 
output/SMAP_EASEv2_M09_GLOBAL/rs/ens0000/Y2017/M10/CURRENT.landpert_internal_rst.20171016_0000: [FAILED]*!?#$*
**gnuglobalcs** fail in assim: 
output/CF0180x6C_GLOBAL/rc_out/Y2017/M04/CURRENT.ldas_catparam.20170423_0300z.bin: CUR file not found
Here is the run: /discover/nobackup/borescan/SystemTests_1/logs/LDAS/2020-10-07

Note: Matt had in scripts set WRITE_RESTART_BY_OSERVER: YES even before our fails so this is not an issue. We used this since June 23rd, 2020. 
I will test just our develop + Matt's update to GCC 10 to see does this pass. 

cc: @gmao-rreichle @weiyuan-jiang @mathomp4

**Comment by biljanaorescanin** [comment]
Test with develop + GCC 10 fails for gnuglobalcs. Only other change beside GCC10 from time this test passed I see in git log is change MAPL_Base to MAPL. 
@mathomp4 maybe we should go back to old GCC(GCC 9 and an older Baselibs)  just to test do we still pass the test?  If it does then we know for sure it's related to GCC 10. 

cc: @gmao-rreichle @weiyuan-jiang

**Comment by mathomp4** [comment]
I could, though the Baselibs version shouldn't matter much (and for sure MAPL 2.3 needs Baselibs 6.0.16).

**Comment by gmao-rreichle** [comment]
Hi @mathomp4 and @biljanaorescanin : 

Sorry, I'm losing track of where things stand.  Partly, my confusion stems from only just realizing that I had simply assumed that something changed last Friday (Oct 2) based on Matt's email message:

> In trying to fix up some AGCM nightly test issues, I saw that the LDAS GNU tests were still using GCC 9 and an older Baselibs. 
> In order to "bring it in line" with what the current LDAS uses (6.0.16), I'm planning on updating the GNU runs to GCC 10 and 6.0.16.

In re-reading this message, I realize that Matt simply says he was "**_planning_** on updating the GNU runs to GCC 1".
So here's a question: Did anything actually change with the tests on or about last Thu/Fri (Oct 1/2)?

Second, I also now realize that GEOSldas does start running and then fails with a seg fault in the GNUGLOBALCS/assim test, contrary to what I said at a meeting with @weiyuan-jiang and @biljanaorescanin yesterday about GEOSldas not running at all.  The latter did happen at some point in the past couple of weeks, but probably not since Thu/Fri of last week. At least today's CURRENT and PREVIOUS log files both show the seg fault.



cc: @weiyuan-jiang

**Comment by biljanaorescanin** [comment]
@gmao-rreichle we are running tests with new GCC 10 and new Baselibs 6.0.16. that did change on Oct 2 if I understood @mathomp4 right. Idea was we move to MAPL 2.3 but for that we needed change @weiyuan-jiang made this week MAPL_Base to MAPL. 
This is from the script gcc9 is commented out. 
LDAS_CUR.csh:   #set GIT_G5FILE = $G5MODULEPATH/6.0.12/g5_modules.gcc9
LDAS_CUR.csh:   set GIT_G5FILE = $G5MODULEPATH/6.0.16/g5_modules.gcc10

cc: @weiyuan-jiang

**Comment by biljanaorescanin** [comment]
@gmao-rreichle  I am running now with old baselibs and gcc 9.

**Comment by biljanaorescanin** [comment]
Addressed with PR #319
