### ISSUE TITLE
Additional info about github cloning in docs?

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOSldas#389]
This is mainly for @gmao-rreichle or @biljanaorescanin. 

I've had some users encounter the "Permission denied (publickey)" error with the SSH GitHub URL, so I [added some bits to the GEOSgcm `README.md`](https://github.com/GEOS-ESM/GEOSgcm#obtain-the-model) to attempt to add a bit more specificity to cloning GitHub repos. Since users might see that GitHub offers more than one way to get a repo (HTTPS, SSH, GitHub CLI), I stayed on the side of completeness and talked about all three.

The GEOSldas `README.md` and docs are much more complex, but if you like, the same could be done here. If nothing else, I/we/you could add the bits about the

**Comment by gmao-rreichle** [comment]
Hi @mathomp4 
Thanks for the offer to improve the documentation, which is always appreciated!
After comparing the README.md files in GEOSgcm and GEOSldas, I would much prefer to make only minimal changes to the GEOSldas README.md file.  I've spent a good amount of effort to compose a set of complete yet concise instructions on how to get started with GEOSldas.  It's not perfect, but I think it's decent as it is right now.  One of the assumptions in the GEOSldas README file is that users are already set up to use "git clone" in some way.  Because the instructions to set up and use git with GitHub are not specific to GEOSldas, I don't think the README.md file is the right place for them.  
The section "Obtain the model" in the GEOSgcm README.md file is almost entirely generic except for the string [GEOSgcm], which occurs only three times in the instructions and could be replaced with any Fixture name.  I think it would be best to put these instructions into a separate document, either a Wiki page or a src code file.  Then the README.md file could just point to them, something like:
"See instruction for setting up git on GitHub here."
This would be minimally invasive in the GEOSldas README.md file and could also be applied to the GEOSgcm README.md file, as well as the README.md in any other GEOS-ESM Fixture.
I don't know how generic these instructions are.  I imagine there might also be some GitHub help page. 
Does that make sense? 
cc: @biljanaorescanin
